---
title: "Vis Assignment 4"
author: "Aron Lesser"
date: "10/1/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(osmdata)
library(opentripplanner)
library(tidyverse)
library(sf)
library(ggthemes)
library(ggspatial)
library(raster)
library(dplyr)

```


All of the same for Boston


# Getting data on hospitals in Boston
```{r}
CPL_libraries <- st_read(
  "http://bostonopendata-boston.opendata.arcgis.com/datasets/8f1e5741a4ee4c0f82925d17aab3c002_2.kml?outSR=%7B%22latestWkid%22%3A2249%2C%22wkid%22%3A102686%7D") %>%
filter(Name %in% c("Boston Medical Center - Menino Campus", "Tufts Medical Center", "Mass General Hospital", "Carney Hospital", "Beth Isreal Deaconess medical Center - East Campus"))

```

Downloading the map
```{r}
#opq(bbox = 'Boston MA USA') %>%
#  add_osm_feature(key = 'highway') %>%
#  osmdata_xml(file = 'OTP/graphs/default/boston_streets.osm')
```

Getting SF Features on the Boston Map

```{r}

MA_state_plane <- "+proj=lcc +lat_1=41.71666666666667 +lat_2=42.68333333333333 +lat_0=41 +lon_0=-71.5 +x_0=200000 +y_0=750000 +ellps=GRS80 +units=m +no_defs"

boston_street_features <- opq(bbox = 'Boston MA USA') %>%
  add_osm_feature(key = 'highway') %>%
  osmdata_sf()

boston_streets <- boston_street_features$osm_lines %>%
  st_transform(crs = MA_state_plane)
```


Building a graph
```{r}
path_data <- file.path(getwd(), "OTP")
path_otp <- paste(path_data, "otp.jar",sep = "/")

otp_build_graph(otp = path_otp, dir = path_data, memory = 1024) 
```

Running OTP

```{r}
otp_setup(otp = path_otp, dir = path_data, memory =1024)

otpcon <- otp_connect()
```


Creating the isochrones around the hospitals in Boston

```{r}
iso_10min_walk <- 
  otp_isochrone(otpcon = otpcon, fromPlace = CPL_libraries, 
                mode = "WALK", cutoffSec = 600) %>%
  st_transform(crs = MA_state_plane) %>%
  mutate(mode = "walk")

iso_10min_drive <- 
  otp_isochrone(otpcon = otpcon, fromPlace = CPL_libraries, 
                mode = "CAR", cutoffSec = 600) %>%
  st_transform(crs = MA_state_plane) %>%
  mutate(mode = "drive")

iso_all_modes <- rbind(iso_10min_drive, iso_10min_walk)

otp_stop()
```

Plotting the isochrones

```{r}
right_side <- st_bbox(iso_all_modes)$xmax
left_side  <- st_bbox(iso_all_modes)$xmin
top_side <- st_bbox(iso_all_modes)$ymax
bottom_side <- st_bbox(iso_all_modes)$ymin

ggplot(iso_all_modes) +
  annotation_map_tile(zoomin = 0, type = "cartolight", progress = "none") +
  geom_sf(aes(fill = mode), alpha = 0.5) +
  geom_sf(data = CPL_libraries) +
  coord_sf(xlim = c(left_side, right_side), 
           ylim = c(bottom_side, top_side), expand = FALSE) +
  scale_fill_viridis_d(name = "Area that is reachable within 5 minutes",
                       labels = c("By car", "By foot")) +
  theme_map() +
  labs(caption = "Basemap Copyright OpenStreetMap contributors")
```

Calculating and comparing isochrone areas

```{r}
iso_areas <- iso_all_modes %>%
  mutate(area = st_area(iso_all_modes)) %>%
  st_set_geometry(NULL) %>%
  pivot_wider(names_from = mode, values_from = area) 

ggplot(iso_areas, 
       aes(x = as.numeric(walk), y = as.numeric(drive))) +
  geom_point() +
  scale_x_continuous(name = 
            "Area within a five-minute walking distance\nof a hospital\n(square km)",
            breaks = breaks <- seq(10000, 130000, by = 20000),
            labels = breaks / 1000000) +
  scale_y_continuous(name = 
            "Area within a five-minute driving distance\nof a hospital\n(square km)",
            breaks = breaks <- seq(0, 700000, by = 100000),
            labels = breaks / 1000000) +
  theme_bw()

```

